
spring:
  dubbo:
    application: manage-web
    registry:
      address: 192.168.44.130:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.atguigu.gmall
    consumer:
      timeout: 6000
      check: false
server:
  port: 8081
