spring:
  dubbo:
    application: item-web
    registry:
      address: 192.168.44.130:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.atguigu.gmall
    consumer:
      timeout: 600000
      check: false
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
server:
  port: 8082

