server:
  port: 8080
spring:
  dubbo:
    application: user-web
    registry:
      address: 192.168.44.128:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.atguigu.gmall
    consumer:
      timeout: 6000
      check: false